// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkM5599_YbseJInK6gkZM3Oy8E4rS4mG8',
    appId: '1:926740165698:web:bfad1cdb5f76b7687169db',
    messagingSenderId: '926740165698',
    projectId: 'drzaighy',
    authDomain: 'drzaighy.firebaseapp.com',
    storageBucket: 'drzaighy.firebasestorage.app',
    measurementId: 'G-P1FXLRT7EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8DZNhxfyFULd2cGQMPyJZ9BfMM5t7Eo',
    appId: '1:926740165698:android:9732628029f7538c7169db',
    messagingSenderId: '926740165698',
    projectId: 'drzaighy',
    storageBucket: 'drzaighy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2rCUERNJ4ip-Y9TqHw2MK_NpTRbSZncc',
    appId: '1:926740165698:ios:10bd5db08b61f65f7169db',
    messagingSenderId: '926740165698',
    projectId: 'drzaighy',
    storageBucket: 'drzaighy.firebasestorage.app',
    iosBundleId: 'com.example.doctorassistent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2rCUERNJ4ip-Y9TqHw2MK_NpTRbSZncc',
    appId: '1:926740165698:ios:10bd5db08b61f65f7169db',
    messagingSenderId: '926740165698',
    projectId: 'drzaighy',
    storageBucket: 'drzaighy.firebasestorage.app',
    iosBundleId: 'com.example.doctorassistent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkM5599_YbseJInK6gkZM3Oy8E4rS4mG8',
    appId: '1:926740165698:web:6c80d4ff11376ac57169db',
    messagingSenderId: '926740165698',
    projectId: 'drzaighy',
    authDomain: 'drzaighy.firebaseapp.com',
    storageBucket: 'drzaighy.firebasestorage.app',
    measurementId: 'G-RSXT4H2DJ4',
  );
}
